name: JavaCI with Maven on Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11.0.28-temurin', '17.0.16+8-temurin']

    name: Build with Java ${{ matrix.java }} on Linux
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Build with Maven
        run: mvn -f DummyProject/myproject/pom.xml clean verify
