name: JavaCI with Maven on Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8.0.362+8', '11.0.20+101', '17.0.16+8']  # Linux supports all three

    name: Build with Java ${{ matrix.java }} on Linux
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Build with Maven
        run: mvn -f DummyProject/myproject/pom.xml clean verify
