name: JavaCI with Maven for PR

on:
  pull_request:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # test against several OSes:
        os: [macos-latest, windows-latest]

    name: Build with Java8 on ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: mvn -f com.examples.myproject/pom.xml clean verify
